name: Run Bot

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        default: 'production'

env:
  PYTHON_VERSION: "3.10.13"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir

    - name: Run Bot with logging
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        python -u bot.py 2>&1 | tee bot.log
        echo "### Бот завершил работу ###"
