name: Run Bot

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Изменили версию ОС
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5  # Обновили версию действия
      with:
        python-version: "3.10"  # Добавили кавычки
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: python bot.py
